export { ReactComponent as petsFriendly } from './Pets friendly.svg';
export { ReactComponent as sharedCommonSpace } from './Shared common space.svg';
export { ReactComponent as furnished } from './Furnished.svg';
export { ReactComponent as airConditioning } from './Air conditioning.svg';
export { ReactComponent as smokeFree } from './Smoke free.svg';
export { ReactComponent as indoorWasher } from './Indoor washer.svg';
export { ReactComponent as outdoorParking } from './Outdoor Parking.svg';
export { ReactComponent as indoorParking } from './Indoor Parking.svg';
export { ReactComponent as swimmingPool } from './Swimming pool.svg';
export { ReactComponent as hardwoodFloor } from './Hardwood floor.svg';
export { ReactComponent as elevator } from './Elevator.svg';
export { ReactComponent as gym } from './Gym.svg';
